[package]
name = "qmk-layout-helper"
license = "GPL-3.0-only"
description = "QMK layout viewer"
authors = ["Stephan Rumswinkel"]
repository = "https://github.com/srwi/qmk-layout-helper"
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
qmk-via-api = "0.0.1"
eframe = "0.28.1"